name: Scheduled Kenya Data Scraping

on:
  schedule:
    # Run at 2:00 AM UTC every Monday and Thursday
    - cron: '0 2 * * 1,4'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright psycopg2-binary
          python -m playwright install --with-deps chromium
      
      - name: Run scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd scraper
          python kenya_scraper.py
      
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet kenya_data_full.json || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push if data changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add kenya_data_full.json
          git commit -m "Update Kenya data - $(date +'%Y-%m-%d')"
          git push
